/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as MisCotizacionesRouteImport } from './routes/mis-cotizaciones'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CotizacionNumeroRouteImport } from './routes/cotizacion.$numero'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated.admin.index'
import { Route as ApiPublicWebhookGetnetRouteImport } from './routes/api/public/webhook-getnet'
import { Route as ApiPublicQueryGetnetPaymentRouteImport } from './routes/api/public/query-getnet-payment'
import { Route as ApiPublicCreateGetnetPaymentRouteImport } from './routes/api/public/create-getnet-payment'
import { Route as AuthenticatedAdminUsuariosRouteImport } from './routes/_authenticated.admin.usuarios'
import { Route as AuthenticatedAdminReportesRouteImport } from './routes/_authenticated.admin.reportes'
import { Route as AuthenticatedAdminPedidosRouteImport } from './routes/_authenticated.admin.pedidos'
import { Route as AuthenticatedAdminPagosGetnetRouteImport } from './routes/_authenticated.admin.pagos-getnet'
import { Route as AuthenticatedAdminFinanzasRouteImport } from './routes/_authenticated.admin.finanzas'
import { Route as AuthenticatedAdminEgresosRouteImport } from './routes/_authenticated.admin.egresos'
import { Route as AuthenticatedAdminCotizacionesRouteImport } from './routes/_authenticated.admin.cotizaciones'
import { Route as AuthenticatedAdminConfiguracionRouteImport } from './routes/_authenticated.admin.configuracion'
import { Route as AuthenticatedAdminColoresRouteImport } from './routes/_authenticated.admin.colores'
import { Route as AuthenticatedAdminBuscarRouteImport } from './routes/_authenticated.admin.buscar'
import { Route as AuthenticatedAdminBoletasRouteImport } from './routes/_authenticated.admin.boletas'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const MisCotizacionesRoute = MisCotizacionesRouteImport.update({
  id: '/mis-cotizaciones',
  path: '/mis-cotizaciones',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CotizacionNumeroRoute = CotizacionNumeroRouteImport.update({
  id: '/cotizacion/$numero',
  path: '/cotizacion/$numero',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const ApiPublicWebhookGetnetRoute = ApiPublicWebhookGetnetRouteImport.update({
  id: '/api/public/webhook-getnet',
  path: '/api/public/webhook-getnet',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicQueryGetnetPaymentRoute =
  ApiPublicQueryGetnetPaymentRouteImport.update({
    id: '/api/public/query-getnet-payment',
    path: '/api/public/query-getnet-payment',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicCreateGetnetPaymentRoute =
  ApiPublicCreateGetnetPaymentRouteImport.update({
    id: '/api/public/create-getnet-payment',
    path: '/api/public/create-getnet-payment',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedAdminUsuariosRoute =
  AuthenticatedAdminUsuariosRouteImport.update({
    id: '/admin/usuarios',
    path: '/admin/usuarios',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminReportesRoute =
  AuthenticatedAdminReportesRouteImport.update({
    id: '/admin/reportes',
    path: '/admin/reportes',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminPedidosRoute =
  AuthenticatedAdminPedidosRouteImport.update({
    id: '/admin/pedidos',
    path: '/admin/pedidos',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminPagosGetnetRoute =
  AuthenticatedAdminPagosGetnetRouteImport.update({
    id: '/admin/pagos-getnet',
    path: '/admin/pagos-getnet',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminFinanzasRoute =
  AuthenticatedAdminFinanzasRouteImport.update({
    id: '/admin/finanzas',
    path: '/admin/finanzas',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminEgresosRoute =
  AuthenticatedAdminEgresosRouteImport.update({
    id: '/admin/egresos',
    path: '/admin/egresos',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminCotizacionesRoute =
  AuthenticatedAdminCotizacionesRouteImport.update({
    id: '/admin/cotizaciones',
    path: '/admin/cotizaciones',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminConfiguracionRoute =
  AuthenticatedAdminConfiguracionRouteImport.update({
    id: '/admin/configuracion',
    path: '/admin/configuracion',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminColoresRoute =
  AuthenticatedAdminColoresRouteImport.update({
    id: '/admin/colores',
    path: '/admin/colores',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminBuscarRoute =
  AuthenticatedAdminBuscarRouteImport.update({
    id: '/admin/buscar',
    path: '/admin/buscar',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminBoletasRoute =
  AuthenticatedAdminBoletasRouteImport.update({
    id: '/admin/boletas',
    path: '/admin/boletas',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/mis-cotizaciones': typeof MisCotizacionesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/cotizacion/$numero': typeof CotizacionNumeroRoute
  '/admin/boletas': typeof AuthenticatedAdminBoletasRoute
  '/admin/buscar': typeof AuthenticatedAdminBuscarRoute
  '/admin/colores': typeof AuthenticatedAdminColoresRoute
  '/admin/configuracion': typeof AuthenticatedAdminConfiguracionRoute
  '/admin/cotizaciones': typeof AuthenticatedAdminCotizacionesRoute
  '/admin/egresos': typeof AuthenticatedAdminEgresosRoute
  '/admin/finanzas': typeof AuthenticatedAdminFinanzasRoute
  '/admin/pagos-getnet': typeof AuthenticatedAdminPagosGetnetRoute
  '/admin/pedidos': typeof AuthenticatedAdminPedidosRoute
  '/admin/reportes': typeof AuthenticatedAdminReportesRoute
  '/admin/usuarios': typeof AuthenticatedAdminUsuariosRoute
  '/api/public/create-getnet-payment': typeof ApiPublicCreateGetnetPaymentRoute
  '/api/public/query-getnet-payment': typeof ApiPublicQueryGetnetPaymentRoute
  '/api/public/webhook-getnet': typeof ApiPublicWebhookGetnetRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/mis-cotizaciones': typeof MisCotizacionesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/cotizacion/$numero': typeof CotizacionNumeroRoute
  '/admin/boletas': typeof AuthenticatedAdminBoletasRoute
  '/admin/buscar': typeof AuthenticatedAdminBuscarRoute
  '/admin/colores': typeof AuthenticatedAdminColoresRoute
  '/admin/configuracion': typeof AuthenticatedAdminConfiguracionRoute
  '/admin/cotizaciones': typeof AuthenticatedAdminCotizacionesRoute
  '/admin/egresos': typeof AuthenticatedAdminEgresosRoute
  '/admin/finanzas': typeof AuthenticatedAdminFinanzasRoute
  '/admin/pagos-getnet': typeof AuthenticatedAdminPagosGetnetRoute
  '/admin/pedidos': typeof AuthenticatedAdminPedidosRoute
  '/admin/reportes': typeof AuthenticatedAdminReportesRoute
  '/admin/usuarios': typeof AuthenticatedAdminUsuariosRoute
  '/api/public/create-getnet-payment': typeof ApiPublicCreateGetnetPaymentRoute
  '/api/public/query-getnet-payment': typeof ApiPublicQueryGetnetPaymentRoute
  '/api/public/webhook-getnet': typeof ApiPublicWebhookGetnetRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/auth': typeof AuthRoute
  '/mis-cotizaciones': typeof MisCotizacionesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/cotizacion/$numero': typeof CotizacionNumeroRoute
  '/_authenticated/admin/boletas': typeof AuthenticatedAdminBoletasRoute
  '/_authenticated/admin/buscar': typeof AuthenticatedAdminBuscarRoute
  '/_authenticated/admin/colores': typeof AuthenticatedAdminColoresRoute
  '/_authenticated/admin/configuracion': typeof AuthenticatedAdminConfiguracionRoute
  '/_authenticated/admin/cotizaciones': typeof AuthenticatedAdminCotizacionesRoute
  '/_authenticated/admin/egresos': typeof AuthenticatedAdminEgresosRoute
  '/_authenticated/admin/finanzas': typeof AuthenticatedAdminFinanzasRoute
  '/_authenticated/admin/pagos-getnet': typeof AuthenticatedAdminPagosGetnetRoute
  '/_authenticated/admin/pedidos': typeof AuthenticatedAdminPedidosRoute
  '/_authenticated/admin/reportes': typeof AuthenticatedAdminReportesRoute
  '/_authenticated/admin/usuarios': typeof AuthenticatedAdminUsuariosRoute
  '/api/public/create-getnet-payment': typeof ApiPublicCreateGetnetPaymentRoute
  '/api/public/query-getnet-payment': typeof ApiPublicQueryGetnetPaymentRoute
  '/api/public/webhook-getnet': typeof ApiPublicWebhookGetnetRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/mis-cotizaciones'
    | '/sitemap.xml'
    | '/cotizacion/$numero'
    | '/admin/boletas'
    | '/admin/buscar'
    | '/admin/colores'
    | '/admin/configuracion'
    | '/admin/cotizaciones'
    | '/admin/egresos'
    | '/admin/finanzas'
    | '/admin/pagos-getnet'
    | '/admin/pedidos'
    | '/admin/reportes'
    | '/admin/usuarios'
    | '/api/public/create-getnet-payment'
    | '/api/public/query-getnet-payment'
    | '/api/public/webhook-getnet'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/mis-cotizaciones'
    | '/sitemap.xml'
    | '/cotizacion/$numero'
    | '/admin/boletas'
    | '/admin/buscar'
    | '/admin/colores'
    | '/admin/configuracion'
    | '/admin/cotizaciones'
    | '/admin/egresos'
    | '/admin/finanzas'
    | '/admin/pagos-getnet'
    | '/admin/pedidos'
    | '/admin/reportes'
    | '/admin/usuarios'
    | '/api/public/create-getnet-payment'
    | '/api/public/query-getnet-payment'
    | '/api/public/webhook-getnet'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/mis-cotizaciones'
    | '/sitemap.xml'
    | '/cotizacion/$numero'
    | '/_authenticated/admin/boletas'
    | '/_authenticated/admin/buscar'
    | '/_authenticated/admin/colores'
    | '/_authenticated/admin/configuracion'
    | '/_authenticated/admin/cotizaciones'
    | '/_authenticated/admin/egresos'
    | '/_authenticated/admin/finanzas'
    | '/_authenticated/admin/pagos-getnet'
    | '/_authenticated/admin/pedidos'
    | '/_authenticated/admin/reportes'
    | '/_authenticated/admin/usuarios'
    | '/api/public/create-getnet-payment'
    | '/api/public/query-getnet-payment'
    | '/api/public/webhook-getnet'
    | '/_authenticated/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthRoute: typeof AuthRoute
  MisCotizacionesRoute: typeof MisCotizacionesRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  CotizacionNumeroRoute: typeof CotizacionNumeroRoute
  ApiPublicCreateGetnetPaymentRoute: typeof ApiPublicCreateGetnetPaymentRoute
  ApiPublicQueryGetnetPaymentRoute: typeof ApiPublicQueryGetnetPaymentRoute
  ApiPublicWebhookGetnetRoute: typeof ApiPublicWebhookGetnetRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mis-cotizaciones': {
      id: '/mis-cotizaciones'
      path: '/mis-cotizaciones'
      fullPath: '/mis-cotizaciones'
      preLoaderRoute: typeof MisCotizacionesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cotizacion/$numero': {
      id: '/cotizacion/$numero'
      path: '/cotizacion/$numero'
      fullPath: '/cotizacion/$numero'
      preLoaderRoute: typeof CotizacionNumeroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/public/webhook-getnet': {
      id: '/api/public/webhook-getnet'
      path: '/api/public/webhook-getnet'
      fullPath: '/api/public/webhook-getnet'
      preLoaderRoute: typeof ApiPublicWebhookGetnetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/query-getnet-payment': {
      id: '/api/public/query-getnet-payment'
      path: '/api/public/query-getnet-payment'
      fullPath: '/api/public/query-getnet-payment'
      preLoaderRoute: typeof ApiPublicQueryGetnetPaymentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/create-getnet-payment': {
      id: '/api/public/create-getnet-payment'
      path: '/api/public/create-getnet-payment'
      fullPath: '/api/public/create-getnet-payment'
      preLoaderRoute: typeof ApiPublicCreateGetnetPaymentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/usuarios': {
      id: '/_authenticated/admin/usuarios'
      path: '/admin/usuarios'
      fullPath: '/admin/usuarios'
      preLoaderRoute: typeof AuthenticatedAdminUsuariosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/reportes': {
      id: '/_authenticated/admin/reportes'
      path: '/admin/reportes'
      fullPath: '/admin/reportes'
      preLoaderRoute: typeof AuthenticatedAdminReportesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/pedidos': {
      id: '/_authenticated/admin/pedidos'
      path: '/admin/pedidos'
      fullPath: '/admin/pedidos'
      preLoaderRoute: typeof AuthenticatedAdminPedidosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/pagos-getnet': {
      id: '/_authenticated/admin/pagos-getnet'
      path: '/admin/pagos-getnet'
      fullPath: '/admin/pagos-getnet'
      preLoaderRoute: typeof AuthenticatedAdminPagosGetnetRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/finanzas': {
      id: '/_authenticated/admin/finanzas'
      path: '/admin/finanzas'
      fullPath: '/admin/finanzas'
      preLoaderRoute: typeof AuthenticatedAdminFinanzasRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/egresos': {
      id: '/_authenticated/admin/egresos'
      path: '/admin/egresos'
      fullPath: '/admin/egresos'
      preLoaderRoute: typeof AuthenticatedAdminEgresosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/cotizaciones': {
      id: '/_authenticated/admin/cotizaciones'
      path: '/admin/cotizaciones'
      fullPath: '/admin/cotizaciones'
      preLoaderRoute: typeof AuthenticatedAdminCotizacionesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/configuracion': {
      id: '/_authenticated/admin/configuracion'
      path: '/admin/configuracion'
      fullPath: '/admin/configuracion'
      preLoaderRoute: typeof AuthenticatedAdminConfiguracionRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/colores': {
      id: '/_authenticated/admin/colores'
      path: '/admin/colores'
      fullPath: '/admin/colores'
      preLoaderRoute: typeof AuthenticatedAdminColoresRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/buscar': {
      id: '/_authenticated/admin/buscar'
      path: '/admin/buscar'
      fullPath: '/admin/buscar'
      preLoaderRoute: typeof AuthenticatedAdminBuscarRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/boletas': {
      id: '/_authenticated/admin/boletas'
      path: '/admin/boletas'
      fullPath: '/admin/boletas'
      preLoaderRoute: typeof AuthenticatedAdminBoletasRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAdminBoletasRoute: typeof AuthenticatedAdminBoletasRoute
  AuthenticatedAdminBuscarRoute: typeof AuthenticatedAdminBuscarRoute
  AuthenticatedAdminColoresRoute: typeof AuthenticatedAdminColoresRoute
  AuthenticatedAdminConfiguracionRoute: typeof AuthenticatedAdminConfiguracionRoute
  AuthenticatedAdminCotizacionesRoute: typeof AuthenticatedAdminCotizacionesRoute
  AuthenticatedAdminEgresosRoute: typeof AuthenticatedAdminEgresosRoute
  AuthenticatedAdminFinanzasRoute: typeof AuthenticatedAdminFinanzasRoute
  AuthenticatedAdminPagosGetnetRoute: typeof AuthenticatedAdminPagosGetnetRoute
  AuthenticatedAdminPedidosRoute: typeof AuthenticatedAdminPedidosRoute
  AuthenticatedAdminReportesRoute: typeof AuthenticatedAdminReportesRoute
  AuthenticatedAdminUsuariosRoute: typeof AuthenticatedAdminUsuariosRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminBoletasRoute: AuthenticatedAdminBoletasRoute,
  AuthenticatedAdminBuscarRoute: AuthenticatedAdminBuscarRoute,
  AuthenticatedAdminColoresRoute: AuthenticatedAdminColoresRoute,
  AuthenticatedAdminConfiguracionRoute: AuthenticatedAdminConfiguracionRoute,
  AuthenticatedAdminCotizacionesRoute: AuthenticatedAdminCotizacionesRoute,
  AuthenticatedAdminEgresosRoute: AuthenticatedAdminEgresosRoute,
  AuthenticatedAdminFinanzasRoute: AuthenticatedAdminFinanzasRoute,
  AuthenticatedAdminPagosGetnetRoute: AuthenticatedAdminPagosGetnetRoute,
  AuthenticatedAdminPedidosRoute: AuthenticatedAdminPedidosRoute,
  AuthenticatedAdminReportesRoute: AuthenticatedAdminReportesRoute,
  AuthenticatedAdminUsuariosRoute: AuthenticatedAdminUsuariosRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthRoute: AuthRoute,
  MisCotizacionesRoute: MisCotizacionesRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  CotizacionNumeroRoute: CotizacionNumeroRoute,
  ApiPublicCreateGetnetPaymentRoute: ApiPublicCreateGetnetPaymentRoute,
  ApiPublicQueryGetnetPaymentRoute: ApiPublicQueryGetnetPaymentRoute,
  ApiPublicWebhookGetnetRoute: ApiPublicWebhookGetnetRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
